
INSERT INTO HOTEL(CODE,NAME,RATING) VALUES(1,'LAKEWOOD',3);
INSERT INTO HOTEL(CODE,NAME,RATING) VALUES(2,'BRIDGEWOOD',4);
INSERT INTO HOTEL(CODE,NAME,RATING) VALUES(3,'RIDGEWOOD',5);



INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(1,'REGULAR','WEEKDAY',110.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(1,'REGULAR','WEEKDAY',80.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(2,'REGULAR','WEEKDAY',160.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(2,'REWARDS','WEEKDAY',110.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(3,'REGULAR','WEEKDAY',220.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(3,'REWARDS','WEEKDAY',100.0);

INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(1,'REGULAR','WEEKEND',90.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(1,'REWARDS','WEEKEND',80.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(2,'REGULAR','WEEKEND',60.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(2,'REWARDS','WEEKEND',50.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(3,'REGULAR','WEEKEND',150.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(3,'REWARDS','WEEKEND',40.0);
