
INSERT INTO HOTEL(CODE,NAME) VALUES(1,'LAKEWOOD');
INSERT INTO HOTEL(CODE,NAME) VALUES(2,'BRIDGEWOOD');
INSERT INTO HOTEL(CODE,NAME) VALUES(3,'RIDGEWOOD');



INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(1,'REGULAR',true,110.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(1,'REWARDS',true,80.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(2,'REGULAR',true,160.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(2,'REWARDS',true,110.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(3,'REGULAR',true,220.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(3,'REWARDS',true,100.0);

INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(1,'REGULAR',false,90.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(1,'REWARDS',false,80.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(2,'REGULAR',false,60.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(2,'REWARDS',false,50.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(3,'REGULAR',false,150.0);
INSERT INTO HOTEL_PRICE(CODE,CUSTOMER_TYPE,DAY_TYPE,PRICE) VALUES(3,'REWARDS',false,40.0);
